version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: book-exchange-web
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./:/app
    # Levanta Uvicorn apuntando a main:app en modo reload para desarrollo
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  db:
    image: postgres:15-alpine
    container_name: book-exchange-db
    env_file:
      - .env
    # Mapear puerto 5433 del host al 5432 del contenedor
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    # Volumen persistente para datos de PostgreSQL
