version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: book-exchange-web
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./:/app
    # Start Uvicorn pointing at main:app in reload mode for dev
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  db:
    image: postgres:15-alpine
    container_name: book-exchange-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: book_exchange
    # Map host port 5433 to container 5432 to avoid conflicts
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  # Persistent volume for PostgreSQL data
  pgdata:
