version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: book-exchange-web
    env_file:
      - .env         # coloca aquí SECRET_KEY, DATABASE_URL, etc.
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./:/app
    command: ["poetry", "run", "uvicorn", "book_exchange_app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  db:
    image: postgres:15-alpine
    container_name: book-exchange-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: book_exchange
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
