version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: book-exchange-web
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./:/app
    command:
      - uvicorn
      - main:app
      - --host
      - "0.0.0.0"
      - --port
      - "8000"
      - --reload

  db:
    image: postgres:15-alpine
    container_name: book-exchange-db
    env_file:
      - .env
    environment:
      # Importamos desde .env
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      # mapeo host → contenedor (pero el web se conecta a "db:5432" internamente)
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
